import { createApp } from "vue";
import ElementPlus from "element-plus";
import "element-plus/dist/index.css";
import MdEditor from "md-editor-v3";
import "md-editor-v3/lib/style.css";
import App from "./App.vue";
import Popover from "vue3-popover";
import "vue3-popover/style.css";
const app = createApp(App);
app.component("MdEditor", MdEditor);
app.use(Popover);
app.use(ElementPlus);
app.mount("#app");
